### PR TITLE
implemented grunt automation.

### PR DESCRIPTION
**Pull request by juzmach**

### CODE REVIEW

**Comment by Tsarpf** [comment]
No new commits still?

**Comment by Tsarpf** [comment]
Just saying that small pull requests that handle one thing each are easier to review, so we should prefer that. But if everything you're working on just has to be done in one that's fine.

**Comment by juzmach** [comment]
I've been too busy finishing my tsoha so I haven't been able to look into this branch. I have the Docker Compose stuff I've been working on in another branch that can be merged separately. I'll be able to fix this branch next week. If you like, we can close this pull request and I'll make another when the fixes are completed.

**Comment by Tsarpf** [comment]
Didn't mean to rush you. Just wanted to point out the separation thang. But that sounds good, no need to close this; we can just keep it open

**Comment by juzmach** [comment]
Now that vagrant environment is working I'll be able to look into the wiredep problem.

**Comment by Tsarpf** [comment]
Running "wiredep:task" (wiredep) task
Warning: Error: bootstrap is not installed. Try running `bower install`. Use --force to continue.

Aborted due to warnings.

**Comment by Tsarpf** [comment]
This is annoying as fuck to configure. At the moment browser console looks like this:

localhost/:6 GET http://localhost:3000/public/libs/bootstrap/dist/css/bootstrap.css 
localhost/:40 GET http://localhost:3000/public/libs/jquery/dist/jquery.js 
localhost/:41 GET http://localhost:3000/public/libs/bootstrap/dist/js/bootstrap.js 
...
etc

and the paths in layout.jade after wiredep has generated them look like this: 
        script(src='../../public/libs/jquery/dist/jquery.js')
        script(src='../../public/libs/bootstrap/dist/js/bootstrap.js')
        script(src='../../public/libs/angular/angular.js')
...
etc

obviously the /public/ part of the path in where the browser is trying to find the libs shouldn't be there

**Comment by Tsarpf** [comment]
Cheers, it should do what it should do

**Pull request merged**
